name: my first workflows
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "Hello World"
            - name: List files
              run: ls
            - name: read file
              run: cat README.md