name: Exploring variable and secrets

on:
    push
env:
    CONTAINER_REGISTRY: docer.io
    IMAGE_NAME: github-action-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

            - name: Docker login
              run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker publish
              run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
                